### ISSUE TITLE
KeyError: 'null_prompt'

### ISSUE THREAD

**Issue by vijetadeshpande** [babylm/evaluation-pipeline#1]
Received following error while testing the code on 'decoder' model

WARNING:root:Tried instantiating `DatasetTemplates` for blimp/causative, but no prompts found. Please ignore this warning if you are creating new prompts for this dataset.
Traceback (most recent call last):
  File "babylm_eval.py", line 62, in <module>
    accuracies[task_title] = accuracy_on_task(task, eval_model, template,
  File "babylm_eval.py", line 16, in accuracy_on_task
    eval_task = lm_eval.get_task_list(task_name, template_names=[template_name])
  File "/home/vdeshpande/BabyLM_challenge/evaluation-pipeline/lm_eval/tasks/__init__.py", line 303, in get_task_list
    return [get_task(task_name, t, **task_kwargs) for t in template_names]
  File "/home/vdeshpande/BabyLM_challenge/evaluation-pipeline/lm_eval/tasks/__init__.py", line 303, in <listcomp>
    return [get_task(task_name, t, **task_kwargs) for t in template_names]
  File "/home/vdeshpande/BabyLM_challenge/evaluation-pipeline/lm_eval/tasks/__init__.py", line 280, in get_task
    template = get_templates(task_name)[template_name]
  File "/home/vdeshpande/miniconda3/envs/babylm_eval/lib/python3.8/site-packages/promptsource/templates.py", line 478, in __getitem__
    return self.templates[self.name_to_id_mapping[template_key]]
KeyError: 'null_prompt'

**Comment by babylm** [comment]
This was due to a bug in the `promptsource` installation. Try re-installing now by navigating to the evaluation-pipeline root directory and running

```
pip install -e ".[dev]"
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
```

**Comment by aaronmueller** [comment]
This is probably due to a version error in `promptsource`. Try re-installing now by navigating to the evaluation-pipeline root directory and running

```
pip install -e ".[dev]"
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
```

**Comment by vijetadeshpande** [comment]
It worked. Thank you!

**Comment by aaronmueller** [comment]
Glad to hear! Thanks for helping us fix that instruction. :)
