### ISSUE TITLE
"Cannot handle batch sizes > 1 if no padding token is defined." AssertionError: Cannot handle batch sizes > 1 if no padding token is defined.

### ISSUE THREAD

**Issue by vijetadeshpande** [babylm/evaluation-pipeline#5]
I am getting the following error for a 'decoder' model

Traceback (most recent call last):                                                                                                                                                  
  File "finetune_classification.py", line 720, in <module>                                                                                                                          
    main()                                                                                                                                                                          
  File "finetune_classification.py", line 627, in main                                                                                                                              
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/transformers/trainer.py", line 1547, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/transformers/trainer.py", line 1791, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/transformers/trainer.py", line 2539, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/transformers/trainer.py", line 2571, in compute_loss
    outputs = model(**inputs)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vdeshpande/miniconda3/envs/babylm_env/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1393, in forward
    ), "Cannot handle batch sizes > 1 if no padding token is defined."
AssertionError: Cannot handle batch sizes > 1 if no padding token is defined.

**Comment by aaronmueller** [comment]
Looks like you'll need to define a padding token for your model. Try setting the padding token to the EOS token, like this (adapted from [this StackOverflow post](https://stackoverflow.com/a/70278116)):

```
# instantiate your model and tokenizer
model = GPT2ForSequenceClassification.from_pretrained(your_model_path)
tokenizer = GPT2ForSequenceClassification.from_pretrained(your_model_path)
# set the pad token in the tokenizer and model
tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = model.config.eos_token_id
# save your model and tokenizer
model.save_pretrained(your_model_path)
tokenizer.save_pretrained(your_model_path)
```

Let me know if this works!

**Comment by aaronmueller** [comment]
Closing this due to inactivity. If there are any more issues, feel free to message me [on the BabyLM slack](https://join.slack.com/t/babylmchallenge/shared_invite/zt-1s8el4mro-qvVO447l3POBZcUNvMWQcg) or to reopen this issue.

**Comment by vvnchristo** [comment]
> tokenizer.pad_token = tokenizer.eos_token

This did not work for me. Anything else that I can try?

**Comment by brendanartley** [comment]
@vvnchristo, you have to set the model config. This should work for you.

```
model.config.pad_token_id = tokenizer.pad_token_id
```
