### ISSUE TITLE
Blimp evaluation failing due to lack of prompts

### ISSUE THREAD

**Issue by rahular** [babylm/evaluation-pipeline#8]
Hi I am trying to evaluate my model on Blimp and getting the following error

```
WARNING:root:Tried instantiating `DatasetTemplates` for blimp/causative, but no prompts found. Please ignore this warning if you are creating new prompts for this dataset.
Traceback (most recent call last):
  File "/home/mila/r/rahul.aralikatte/babylm-eval/babylm_eval.py", line 62, in <module>
    accuracies[task_title] = accuracy_on_task(task, eval_model, template,
  File "/home/mila/r/rahul.aralikatte/babylm-eval/babylm_eval.py", line 16, in accuracy_on_task
    eval_task = lm_eval.get_task_list(task_name, template_names=[template_name])
  File "/home/mila/r/rahul.aralikatte/babylm-eval/lm_eval/tasks/__init__.py", line 303, in get_task_list
    return [get_task(task_name, t, **task_kwargs) for t in template_names]
  File "/home/mila/r/rahul.aralikatte/babylm-eval/lm_eval/tasks/__init__.py", line 303, in <listcomp>
    return [get_task(task_name, t, **task_kwargs) for t in template_names]
  File "/home/mila/r/rahul.aralikatte/babylm-eval/lm_eval/tasks/__init__.py", line 280, in get_task
    template = get_templates(task_name)[template_name]
  File "/home/mila/r/rahul.aralikatte/miniconda3/envs/babylm-eval/lib/python3.9/site-packages/promptsource/templates.py", line 478, in __getitem__
    return self.templates[self.name_to_id_mapping[template_key]]
KeyError: 'null_prompt'
```

I have installed `promptsource==0.2.3` as mentioned [here](https://github.com/babylm/evaluation-pipeline/issues/4#issuecomment-1502280505)

**Comment by aaronmueller** [comment]
Installing promptsource from pip will only work on the `colab` branch; the pip version does not include the prompts we use for BLiMP tasks. If you're on the `main` branch, install promptsource this way:

`pip install promptsource@git+https://github.com/bigscience-workshop/promptsource@eval-hackathon`

Alternatively, follow the instructions on the README:

```
git clone https://github.com/babylm/evaluation-pipeline
cd evaluation-pipeline
pip install -e ".[dev]"
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
```

The `pip install -e ".[dev]"` step installs promptsource from git, rather than pip.

**Comment by rahular** [comment]
Thanks! With this, I am facing the same issue as #4. Anyway, I could install it with a slight variation of your command.

```
pip install --verbose -e git+https://github.com/bigscience-workshop/promptsource.git@eval-hackathon#egg=promptsource

```
